/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: schema.json
export type PublicationReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "publication"
}

export type WorkReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "work"
}

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: "span"
        _key: string
      }>
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote"
      listItem?: "bullet" | "number"
      markDefs?: Array<
        | {
            href: string
            openInNewTab?: boolean
            _type: "link"
            _key: string
          }
        | {
            reference: PublicationReference | WorkReference
            _type: "relatedContentLink"
            _key: string
          }
      >
      level?: number
      _type: "block"
      _key: string
    }
  | ({
      _key: string
    } & PortableImage)
  | ({
      _key: string
    } & CodeBlock)
  | ({
      _key: string
    } & Callout)
  | ({
      _key: string
    } & TableBlock)
  | ({
      _key: string
    } & RelatedContent)
>

export type RelatedContent = {
  _type: "relatedContent"
  reference: PublicationReference | WorkReference
  label?: string
}

export type TableBlock = {
  _type: "tableBlock"
  caption?: string
  hasHeaderRow?: boolean
  rows: Array<
    {
      _key: string
    } & TableRow
  >
}

export type TableRow = {
  _type: "tableRow"
  cells: Array<string>
}

export type Callout = {
  _type: "callout"
  tone: "note" | "tip" | "warning"
  title?: string
  content: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: "span"
      _key: string
    }>
    style?: "normal"
    listItem?: "bullet" | "number"
    markDefs?: Array<{
      href: string
      openInNewTab?: boolean
      _type: "link"
      _key: string
    }>
    level?: number
    _type: "block"
    _key: string
  }>
}

export type CodeBlock = {
  _type: "codeBlock"
  code: string
  language:
    | "text"
    | "bash"
    | "css"
    | "groq"
    | "html"
    | "javascript"
    | "json"
    | "jsx"
    | "typescript"
    | "tsx"
  filename?: string
}

export type SanityImageAssetReference = {
  _ref: string
  _type: "reference"
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset"
}

export type PortableImage = {
  _type: "portableImage"
  image: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: "image"
  }
  alt: string
  caption?: string
}

export type Skill = {
  _type: "skill"
  title: string
  tags: Array<string>
}

export type SocialProfile = {
  _type: "socialProfile"
  platform: "x" | "instagram" | "linkedin" | "github" | "scholar"
  username: string
  url: string
  isHidden?: boolean
}

export type Institute = {
  _type: "institute"
  name: string
  website?: string
}

export type ExperienceCompany = {
  _type: "experienceCompany"
  isAnonymized?: boolean
  name?: string
  website?: string
  location: string
}

export type SiteSettings = {
  _id: string
  _type: "siteSettings"
  _createdAt: string
  _updatedAt: string
  _rev: string
  skills: Array<
    {
      _key: string
    } & Skill
  >
  socialMedia: Array<
    {
      _key: string
    } & SocialProfile
  >
  interests: Array<string>
}

export type Academic = {
  _id: string
  _type: "academic"
  _createdAt: string
  _updatedAt: string
  _rev: string
  institute: Institute
  degree: string
  field: string
  timeline: string
}

export type Experience = {
  _id: string
  _type: "experience"
  _createdAt: string
  _updatedAt: string
  _rev: string
  company: ExperienceCompany
  timeline: string
  role: string
  key_contributions: PortableText
}

export type Work = {
  _id: string
  _type: "work"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description: string
  tags: Array<string>
  metadata: {
    isFeatured?: boolean
    projectUrl?: string
    repositoryUrl?: string
    key_contributions: PortableText
  }
}

export type SanityImageCrop = {
  _type: "sanity.imageCrop"
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot"
  x: number
  y: number
  height: number
  width: number
}

export type Publication = {
  _id: string
  _type: "publication"
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  abstract: string
  authors: Array<string>
  metadata: {
    journal?: string
    status:
      "in_preparation" | "submitted" | "under_review" | "accepted" | "published"
    year?: number
    doi?: string
    isFeatured?: boolean
  }
}

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch"
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: "sanity.imagePalette"
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions"
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata"
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: "sanity.fileAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData"
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: "sanity.imageAsset"
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: "geopoint"
  lat?: number
  lng?: number
  alt?: number
}

export type Slug = {
  _type: "slug"
  current: string
  source?: string
}

export type AllSanitySchemaTypes =
  | PublicationReference
  | WorkReference
  | PortableText
  | RelatedContent
  | TableBlock
  | TableRow
  | Callout
  | CodeBlock
  | SanityImageAssetReference
  | PortableImage
  | Skill
  | SocialProfile
  | Institute
  | ExperienceCompany
  | SiteSettings
  | Academic
  | Experience
  | Work
  | SanityImageCrop
  | SanityImageHotspot
  | Publication
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
  | Slug

// Source: src/sanity/queries/profile.ts
// Variable: EXPERIENCE_QUERY
// Query: *[_type == "experience"]  | order(_createdAt desc) {    "company": select(      company.isAnonymized == true => {        "name": "Confidential organization",        "website": null,        "location": company.location,        "isAnonymized": true      },      {        "name": coalesce(company.name, "Organization"),        "website": company.website,        "location": company.location,        "isAnonymized": false      }    ),    timeline,    role,    "key_contributions": coalesce(key_contributions[]{        ...,  _type == "portableImage" => {    image {      ...,      asset->{        _id,        url,        metadata {          dimensions,          lqip        }      }    }  },  _type == "callout" => {    content[]{...}  },  _type == "tableBlock" => {    rows[]{      _key,      cells    }  },  _type == "relatedContent" => {    reference->{      _id,      _type,      title,      "slug": slug.current    }  },  _type == "block" => {    markDefs[]{      ...,      _type == "relatedContentLink" => {        reference->{          _id,          _type,          title,          "slug": slug.current        }      }    }  }    }, []),      "createdAt": _createdAt,  "updatedAt": _updatedAt  }
export type EXPERIENCE_QUERY_RESULT = Array<{
  company:
    | {
        name: string | "Organization"
        website: string | null
        location: string
        isAnonymized: false
      }
    | {
        name: "Confidential organization"
        website: null
        location: string
        isAnonymized: true
      }
  timeline: string
  role: string
  key_contributions: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: "span"
          _key: string
        }>
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal"
        listItem?: "bullet" | "number"
        markDefs: Array<
          | {
              href: string
              openInNewTab?: boolean
              _type: "link"
              _key: string
            }
          | {
              reference:
                | {
                    _id: string
                    _type: "publication"
                    title: string
                    slug: null
                  }
                | {
                    _id: string
                    _type: "work"
                    title: string
                    slug: null
                  }
              _type: "relatedContentLink"
              _key: string
            }
        > | null
        level?: number
        _type: "block"
        _key: string
      }
    | {
        _key: string
        _type: "callout"
        tone: "note" | "tip" | "warning"
        title?: string
        content: Array<{
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
          }>
          style?: "normal"
          listItem?: "bullet" | "number"
          markDefs?: Array<{
            href: string
            openInNewTab?: boolean
            _type: "link"
            _key: string
          }>
          level?: number
          _type: "block"
          _key: string
        }>
      }
    | {
        _key: string
        _type: "codeBlock"
        code: string
        language:
          | "bash"
          | "css"
          | "groq"
          | "html"
          | "javascript"
          | "json"
          | "jsx"
          | "text"
          | "tsx"
          | "typescript"
        filename?: string
      }
    | {
        _key: string
        _type: "portableImage"
        image: {
          asset: {
            _id: string
            url: string
            metadata: {
              dimensions: SanityImageDimensions | null
              lqip: string | null
            } | null
          } | null
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: "image"
        }
        alt: string
        caption?: string
      }
    | {
        _key: string
        _type: "relatedContent"
        reference:
          | {
              _id: string
              _type: "publication"
              title: string
              slug: null
            }
          | {
              _id: string
              _type: "work"
              title: string
              slug: null
            }
        label?: string
      }
    | {
        _key: string
        _type: "tableBlock"
        caption?: string
        hasHeaderRow?: boolean
        rows: Array<{
          _key: string
          cells: Array<string>
        }>
      }
  >
  createdAt: string
  updatedAt: string
}>

// Source: src/sanity/queries/profile.ts
// Variable: ACADEMIC_HISTORY_QUERY
// Query: *[_type == "academic"]  | order(_createdAt desc) {    "institute": {      "name": institute.name,      "website": institute.website    },    degree,    field,    timeline,      "createdAt": _createdAt,  "updatedAt": _updatedAt  }
export type ACADEMIC_HISTORY_QUERY_RESULT = Array<{
  institute: {
    name: string
    website: string | null
  }
  degree: string
  field: string
  timeline: string
  createdAt: string
  updatedAt: string
}>

// Source: src/sanity/queries/profile.ts
// Variable: SOCIAL_PROFILES_QUERY
// Query: coalesce(*[_id == "siteSettings"][0].socialMedia, [])[]{    _key,    platform,    username,    url,    "isHidden": isHidden == true  }
export type SOCIAL_PROFILES_QUERY_RESULT =
  | Array<{
      _key: string
      platform: "github" | "instagram" | "linkedin" | "scholar" | "x"
      username: string
      url: string
      isHidden: boolean | false
    }>
  | Array<never>

// Source: src/sanity/queries/publications.ts
// Variable: PUBLICATIONS_LIST_QUERY
// Query: *[_type == "publication"]  | order(metadata.year desc, _createdAt desc) {    title,    abstract,    "authors": coalesce(authors, []),    "metadata": {      "journal": metadata.journal,      "status": metadata.status,      "year": metadata.year,      "doi": metadata.doi,      "isFeatured": metadata.isFeatured == true    },      "createdAt": _createdAt,  "updatedAt": _updatedAt  }
export type PUBLICATIONS_LIST_QUERY_RESULT = Array<{
  title: string
  abstract: string
  authors: Array<string>
  metadata: {
    journal: string | null
    status:
      "accepted" | "in_preparation" | "published" | "submitted" | "under_review"
    year: number | null
    doi: string | null
    isFeatured: boolean | false
  }
  createdAt: string
  updatedAt: string
}>

// Source: src/sanity/queries/work.ts
// Variable: WORK_LIST_QUERY
// Query: *[_type == "work"]  | order(coalesce(metadata.isFeatured, false) desc, _updatedAt desc, _id asc) {    "id": _id,    title,    description,    "tags": coalesce(tags, []),    "metadata": {      "isFeatured": metadata.isFeatured == true,      "projectUrl": metadata.projectUrl,      "repositoryUrl": metadata.repositoryUrl,      "key_contributions": coalesce(metadata.key_contributions[]{          ...,  _type == "portableImage" => {    image {      ...,      asset->{        _id,        url,        metadata {          dimensions,          lqip        }      }    }  },  _type == "callout" => {    content[]{...}  },  _type == "tableBlock" => {    rows[]{      _key,      cells    }  },  _type == "relatedContent" => {    reference->{      _id,      _type,      title,      "slug": slug.current    }  },  _type == "block" => {    markDefs[]{      ...,      _type == "relatedContentLink" => {        reference->{          _id,          _type,          title,          "slug": slug.current        }      }    }  }      }, [])    },      "createdAt": _createdAt,  "updatedAt": _updatedAt  }
export type WORK_LIST_QUERY_RESULT = Array<{
  id: string
  title: string
  description: string
  tags: Array<string>
  metadata: {
    isFeatured: boolean | false
    projectUrl: string | null
    repositoryUrl: string | null
    key_contributions: Array<
      | {
          children?: Array<{
            marks?: Array<string>
            text?: string
            _type: "span"
            _key: string
          }>
          style?: "blockquote" | "h2" | "h3" | "h4" | "normal"
          listItem?: "bullet" | "number"
          markDefs: Array<
            | {
                href: string
                openInNewTab?: boolean
                _type: "link"
                _key: string
              }
            | {
                reference:
                  | {
                      _id: string
                      _type: "publication"
                      title: string
                      slug: null
                    }
                  | {
                      _id: string
                      _type: "work"
                      title: string
                      slug: null
                    }
                _type: "relatedContentLink"
                _key: string
              }
          > | null
          level?: number
          _type: "block"
          _key: string
        }
      | {
          _key: string
          _type: "callout"
          tone: "note" | "tip" | "warning"
          title?: string
          content: Array<{
            children?: Array<{
              marks?: Array<string>
              text?: string
              _type: "span"
              _key: string
            }>
            style?: "normal"
            listItem?: "bullet" | "number"
            markDefs?: Array<{
              href: string
              openInNewTab?: boolean
              _type: "link"
              _key: string
            }>
            level?: number
            _type: "block"
            _key: string
          }>
        }
      | {
          _key: string
          _type: "codeBlock"
          code: string
          language:
            | "bash"
            | "css"
            | "groq"
            | "html"
            | "javascript"
            | "json"
            | "jsx"
            | "text"
            | "tsx"
            | "typescript"
          filename?: string
        }
      | {
          _key: string
          _type: "portableImage"
          image: {
            asset: {
              _id: string
              url: string
              metadata: {
                dimensions: SanityImageDimensions | null
                lqip: string | null
              } | null
            } | null
            media?: unknown
            hotspot?: SanityImageHotspot
            crop?: SanityImageCrop
            _type: "image"
          }
          alt: string
          caption?: string
        }
      | {
          _key: string
          _type: "relatedContent"
          reference:
            | {
                _id: string
                _type: "publication"
                title: string
                slug: null
              }
            | {
                _id: string
                _type: "work"
                title: string
                slug: null
              }
          label?: string
        }
      | {
          _key: string
          _type: "tableBlock"
          caption?: string
          hasHeaderRow?: boolean
          rows: Array<{
            _key: string
            cells: Array<string>
          }>
        }
    >
  }
  createdAt: string
  updatedAt: string
}>

// Query TypeMap
import "@sanity/client"
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "experience"]\n  | order(_createdAt desc) {\n    "company": select(\n      company.isAnonymized == true => {\n        "name": "Confidential organization",\n        "website": null,\n        "location": company.location,\n        "isAnonymized": true\n      },\n      {\n        "name": coalesce(company.name, "Organization"),\n        "website": company.website,\n        "location": company.location,\n        "isAnonymized": false\n      }\n    ),\n    timeline,\n    role,\n    "key_contributions": coalesce(key_contributions[]{\n      \n  ...,\n  _type == "portableImage" => {\n    image {\n      ...,\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions,\n          lqip\n        }\n      }\n    }\n  },\n  _type == "callout" => {\n    content[]{...}\n  },\n  _type == "tableBlock" => {\n    rows[]{\n      _key,\n      cells\n    }\n  },\n  _type == "relatedContent" => {\n    reference->{\n      _id,\n      _type,\n      title,\n      "slug": slug.current\n    }\n  },\n  _type == "block" => {\n    markDefs[]{\n      ...,\n      _type == "relatedContentLink" => {\n        reference->{\n          _id,\n          _type,\n          title,\n          "slug": slug.current\n        }\n      }\n    }\n  }\n\n    }, []),\n    \n  "createdAt": _createdAt,\n  "updatedAt": _updatedAt\n\n  }\n': EXPERIENCE_QUERY_RESULT
    '\n  *[_type == "academic"]\n  | order(_createdAt desc) {\n    "institute": {\n      "name": institute.name,\n      "website": institute.website\n    },\n    degree,\n    field,\n    timeline,\n    \n  "createdAt": _createdAt,\n  "updatedAt": _updatedAt\n\n  }\n': ACADEMIC_HISTORY_QUERY_RESULT
    '\n  coalesce(*[_id == "siteSettings"][0].socialMedia, [])[]{\n    _key,\n    platform,\n    username,\n    url,\n    "isHidden": isHidden == true\n  }\n': SOCIAL_PROFILES_QUERY_RESULT
    '\n  *[_type == "publication"]\n  | order(metadata.year desc, _createdAt desc) {\n    title,\n    abstract,\n    "authors": coalesce(authors, []),\n    "metadata": {\n      "journal": metadata.journal,\n      "status": metadata.status,\n      "year": metadata.year,\n      "doi": metadata.doi,\n      "isFeatured": metadata.isFeatured == true\n    },\n    \n  "createdAt": _createdAt,\n  "updatedAt": _updatedAt\n\n  }\n': PUBLICATIONS_LIST_QUERY_RESULT
    '\n  *[_type == "work"]\n  | order(coalesce(metadata.isFeatured, false) desc, _updatedAt desc, _id asc) {\n    "id": _id,\n    title,\n    description,\n    "tags": coalesce(tags, []),\n    "metadata": {\n      "isFeatured": metadata.isFeatured == true,\n      "projectUrl": metadata.projectUrl,\n      "repositoryUrl": metadata.repositoryUrl,\n      "key_contributions": coalesce(metadata.key_contributions[]{\n        \n  ...,\n  _type == "portableImage" => {\n    image {\n      ...,\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions,\n          lqip\n        }\n      }\n    }\n  },\n  _type == "callout" => {\n    content[]{...}\n  },\n  _type == "tableBlock" => {\n    rows[]{\n      _key,\n      cells\n    }\n  },\n  _type == "relatedContent" => {\n    reference->{\n      _id,\n      _type,\n      title,\n      "slug": slug.current\n    }\n  },\n  _type == "block" => {\n    markDefs[]{\n      ...,\n      _type == "relatedContentLink" => {\n        reference->{\n          _id,\n          _type,\n          title,\n          "slug": slug.current\n        }\n      }\n    }\n  }\n\n      }, [])\n    },\n    \n  "createdAt": _createdAt,\n  "updatedAt": _updatedAt\n\n  }\n': WORK_LIST_QUERY_RESULT
  }
}
