import "./globals.css";
import SideBar from "./components/navigation/SideBar";
import Header from "./components/generic/Header";
import Footer from "./components/generic/Footer";
import GeneralProvider from "./context/GeneralContext";
import { Red_Hat_Display, Inter } from "next/font/google";
import MobileNavToggler from "./components/navigation/MobileNavToggler";

const display = Red_Hat_Display({
  subsets: ["latin"],
  variable: "--display",
  weight: "variable",
});

const inter = Inter({ subsets: ["latin"], variable: "--inter" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="text-primary bg-base-300">
      <body className={`${display.variable} ${inter.variable}`}>
        <GeneralProvider>
          <main className="font-inter relative flex flex-col items-center bg-base-300 w-full h-[100vh] lg:px-28 p-5 overflow-hidden">
            <SideBar />
            {/* <Header /> */}
            <div className="view-port-container w-full h-full bg-base-100/35 scroll-smooth">
              <div className="relative w-full h-auto">{children}</div>
              <Footer />
            </div>
            {/* <MobileNavToggler /> */}
          </main>
        </GeneralProvider>
      </body>
    </html>
  );
}
